- scripts/hostis
Signed-off-by: Konstantin Baierer <konstantin.baierer@bib.uni-mannheim.de>
> Document and structure hostis script

- scripts/startvncserver
Signed-off-by: Konstantin Baierer <konstantin.baierer@bib.uni-mannheim.de>
> shellcheck startvncserver: ``->$(), split DISPLAY export

- README.md
Signed-off-by: Philipp Zumstein <zuphilip@gmail.com>
> Add picture (link) in README.md

- control.php
* Remove unused code in comments.
* Initialize local array.
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> control: Fix more issues found by Scrutinizer

- docs/dist/php-codesniffer.sh
- docs/dist/pre-commit.sh
- docs/dist/ruleset.xml
This PR contains the unmerged commits from #22, improving the php/shell check scripts without the Travis stuff.
Supersedes #33.
> Fix checkers

- FileHandler.class.php
- upload.php
Cleaner version of automatic conversion of office files to pdf.
> PDF conversion of office files

- locale/fr_FR.UTF-8/LC_MESSAGES/palma.po
Signed-off-by: Lena Burger <lburger@mail.uni-mannheim.de>
> Added French-Folder and Translation for "not available"

- locale/zh_CN.UTF-8/LC_MESSAGES/palma.po
> fix some wrong translation and complete translation

- theme/ub-mannheim/common/winvnc-palma.exe
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Remove unneeded dummy file

- locale/lv_LV.UTF-8/LC_MESSAGES/palma.po
Signed-off-by: Polina <polina.potoskueva@gmail.com>
> added a new language (lv)

- locale/es_ES.UTF-8/LC_MESSAGES/palma.po
> Update Spanish translation

- README.md
> Fix image paths in README

- locale/ar.UTF-8/LC_MESSAGES/palma.po
as part of the exercise i translated few strings to Arabic
> translated few more strings

- locale/es_ES.UTF-8/LC_MESSAGES/palma.po
Added some basic single word translations via google translate.
Please also check the file, i looks like there are some issues with the formatting. Sometimes the msgid is empty or there are multiple strings for a single translation msgid
> added some basic translations

- locale/es_ES.UTF-8/LC_MESSAGES/palma.po
The Last-Translator info was edited and yes, I do have my name and email in GitHub
> Spanish translation + Last-Translator added

- DBConnector.class.php
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Add documentation for function checkPermission and simplify code

- locale/ru_RU.UTF-8/LC_MESSAGES/palma.po
Some texts were translated to Russian
> Advanced task for Exercise 1-05

- locale/zh_CN.UTF-8/LC_MESSAGES/palma.po
Change something in zh_CN part translation
> Signed-off-by: bbbbtong <btong@mail.uni-mannheim.de>

- locale/it_IT.UTF-8/LC_MESSAGES/palma.po
Signed-off-by: srankl <srankl@mail.uni-mannheim.de>
> Modified Italian directory

- monitor/palma_analyze
shows number of sessions, users and time per month
> added option: -m for monthly results

- locale/kg_KG.UTF-8/LC_MESSAGES/palma.po
Official language of the Kyrgyz Republic is Kyrgyz language. I hope you will accept my request:)
> added Kyrgyz language translation
